# # main.py
# """
# End-to-End Loan Processing Demo – Retail + SME (Combined)
# =========================================================
# Tabs: Applications (Retail + SME with search + side panel) | Results

# Data is loaded from:
#     retail_applicants.json   ← generated by synthetic_data_generator.py
#     sme_applicants.json      ← generated by synthetic_data_generator.py

# Run:
#     flet run main.py

# Package:
#     flet pack main.py --name "LoanDemo-Final" --icon assets/bank.ico \
#         --add-data "assets;assets" \
#         --add-data "retail_applicants.json;." \
#         --add-data "sme_applicants.json;." \
#         --hidden-import matplotlib --hidden-import sarvamai --hidden-import numpy
# """

# import json
# import random
# import time

# import flet as ft

# from retail_pipeline import RetailPipeline
# from sme_pipeline import SMEPipeline
# from sarvam_utils import stt_from_file, translate_to_hindi

# # ── Lazy-import gauges (matplotlib not required at startup) ──────────────────
# try:
#     from gauges import dscr_gauge, ltv_gauge
#     GAUGES_AVAILABLE = True
# except ImportError:
#     GAUGES_AVAILABLE = False

# # ─────────────────────────────────────────────────────────────────────────────
# # Load synthetic data
# # ─────────────────────────────────────────────────────────────────────────────
# try:
#     with open("retail_applicants.json", "r", encoding="utf-8") as _f:
#         RETAIL_SAMPLES: list = json.load(_f)
#     print(f"✅  Loaded {len(RETAIL_SAMPLES):,} retail applicants")
# except FileNotFoundError:
#     RETAIL_SAMPLES = []
#     print("⚠️  retail_applicants.json not found – run synthetic_data_generator.py first")

# try:
#     with open("sme_applicants.json", "r", encoding="utf-8") as _f:
#         SME_SAMPLES: list = json.load(_f)
#     print(f"✅  Loaded {len(SME_SAMPLES):,} SME applicants")
# except FileNotFoundError:
#     SME_SAMPLES = []
#     print("⚠️  sme_applicants.json not found – run synthetic_data_generator.py first")

# # ─────────────────────────────────────────────────────────────────────────────
# # Pipelines (singleton)
# # ─────────────────────────────────────────────────────────────────────────────
# _retail_pipeline = RetailPipeline()
# _sme_pipeline    = SMEPipeline()


# # ─────────────────────────────────────────────────────────────────────────────
# # Helpers
# # ─────────────────────────────────────────────────────────────────────────────
# def fmt_inr(n) -> str:
#     try:
#         return f"₹{float(n):,.0f}"
#     except Exception:
#         return str(n)


# def kv_row(label: str, value: str) -> ft.Row:
#     return ft.Row([
#         ft.Text(f"{label}:", weight="bold", size=13, width=220, color=ft.colors.BLUE_GREY_200),
#         ft.Text(str(value), size=13, selectable=True, expand=True),
#     ], spacing=8)


# # ─────────────────────────────────────────────────────────────────────────────
# # Main Flet app
# # ─────────────────────────────────────────────────────────────────────────────
# def main(page: ft.Page):
#     page.title       = "Loan Processing Demo – Retail & SME"
#     page.theme_mode  = ft.ThemeMode.DARK
#     page.padding     = 0
#     page.window_width  = 1400
#     page.window_height = 860
#     page.bgcolor     = "#0d1117"
#     page.fonts       = {}

#     # ── Shared state ────────────────────────────────────────────────────────
#     picked_file   = [None]
#     last_result   = [{}]
#     active_mode   = ["retail"]   # "retail" | "sme"

#     # ── File picker ─────────────────────────────────────────────────────────
#     def on_file_picked(e: ft.FilePickerResultEvent):
#         if e.files:
#             picked_file[0] = e.files[0].path
#             page.show_snack_bar(ft.SnackBar(ft.Text(f"Loaded: {e.files[0].name}")))

#     file_picker = ft.FilePicker(on_result=on_file_picked)
#     page.overlay.append(file_picker)

#     # ── Results panel ───────────────────────────────────────────────────────
#     results_col = ft.Column(scroll=ft.ScrollMode.AUTO, spacing=10, expand=True)

#     def show_results(result: dict, mode: str):
#         results_col.controls.clear()
#         last_result[0] = result

#         decision = result.get("decision", "N/A")
#         color    = (
#             ft.colors.GREEN_400  if "APPROVE" in str(decision) else
#             ft.colors.ORANGE_400 if "REVIEW"  in str(decision) else
#             ft.colors.RED_400
#         )

#         # Header chip
#         results_col.controls.append(
#             ft.Container(
#                 ft.Text(f"▶  {decision}", size=22, weight="bold", color=color),
#                 padding=ft.padding.symmetric(horizontal=20, vertical=12),
#                 bgcolor=ft.colors.with_opacity(0.18, color),
#                 border_radius=10,
#             )
#         )

#         # Key metrics
#         if mode == "retail":
#             metrics = [
#                 ("Applicant",         result.get("full_name", result.get("name", "N/A"))),
#                 ("Loan Type",         result.get("loan_type", result.get("type", "N/A"))),
#                 ("City",              result.get("city", "N/A")),
#                 ("CIBIL Score",       result.get("cibil_score", result.get("cibil", "N/A"))),
#                 ("Monthly Income",    fmt_inr(result.get("net_monthly_income", result.get("monthly_income", 0)))),
#                 ("Proposed EMI",      fmt_inr(result.get("proposed_emi", 0))),
#                 ("FOIR Pre-Loan",     f"{result.get('foir_pre_loan', 0):.1f}%"),
#                 ("FOIR Post-Loan",    f"{result.get('foir_post_loan', 0):.1f}% (max {result.get('max_allowed_foir', 50)}%)"),
#                 ("FOIR Status",       result.get("foir_status", "N/A")),
#                 ("Loan Requested",    fmt_inr(result.get("loan_amount_requested", result.get("loan_amt", 0)))),
#                 ("Approved Amount",   fmt_inr(result.get("approved_amount", 0))),
#                 ("Interest Rate",     f"{result.get('interest_rate', 'N/A')}%"),
#                 ("Credit Score",      f"{result.get('final_score', 'N/A')} / 98"),
#                 ("Risk Grade",        result.get("bureau_risk_grade", "N/A")),
#                 ("LTV Ratio",         f"{result.get('ltv_ratio', 0):.1f}%"),
#                 ("NACH UMRN",         result.get("nach_umrn", "N/A")),
#                 ("Loan Account",      result.get("loan_account_number", "N/A")),
#                 ("Disbursement Mode", result.get("disbursement_mode", "N/A")),
#             ]
#         else:
#             metrics = [
#                 ("Business",          result.get("name", result.get("business_name", "N/A"))),
#                 ("Loan Type",         result.get("loan_type", result.get("type", "N/A"))),
#                 ("City",              result.get("city", "N/A")),
#                 ("Industry",          result.get("industry", "N/A")),
#                 ("Annual Turnover",   fmt_inr(result.get("annual_turnover", result.get("turnover", 0)))),
#                 ("Promoter CIBIL",    result.get("promoter_cibil_score", result.get("cibil", "N/A"))),
#                 ("DSCR",              f"{result.get('dscr', 0):.2f}  (≥1.25 required)"),
#                 ("Current Ratio",     result.get("current_ratio", "N/A")),
#                 ("Debt / Equity",     result.get("debt_to_equity", "N/A")),
#                 ("Gross Margin",      f"{result.get('gross_profit_margin', 0):.1f}%"),
#                 ("Financial Health",  f"{result.get('financial_health_score', 0):.1f} / 98"),
#                 ("Collateral Value",  fmt_inr(result.get("collateral_value", 0))),
#                 ("LTV Ratio",         f"{result.get('ltv_ratio', 0):.1f}%"),
#                 ("Risk Score",        f"{result.get('total_score', 'N/A')} / 98"),
#                 ("Risk Grade",        result.get("risk_grade", "N/A")),
#                 ("Loan Requested",    fmt_inr(result.get("loan_amount_requested", result.get("loan_amt", 0)))),
#                 ("Sanctioned Amount", fmt_inr(result.get("sanctioned_amount", 0))),
#                 ("Interest Rate",     f"{result.get('final_interest_rate', 'N/A')}%"),
#                 ("NACH UMRN",         result.get("nach_umrn", "N/A")),
#                 ("Loan Account",      result.get("loan_account_number", "N/A")),
#             ]

#         for label, val in metrics:
#             results_col.controls.append(kv_row(label, val))

#         # Gauge
#         if GAUGES_AVAILABLE:
#             try:
#                 if mode == "sme":
#                     dscr = result.get("dscr", 1.0) or 1.0
#                     img  = dscr_gauge(float(dscr))
#                     results_col.controls.append(
#                         ft.Image(src_base64=img, width=340, height=200, fit=ft.ImageFit.CONTAIN)
#                     )
#                 ltv = result.get("ltv_ratio", 0) or 0
#                 if ltv > 0:
#                     img2 = ltv_gauge(float(ltv))
#                     results_col.controls.append(
#                         ft.Image(src_base64=img2, width=340, height=200, fit=ft.ImageFit.CONTAIN)
#                     )
#             except Exception as ge:
#                 results_col.controls.append(ft.Text(f"Gauge error: {ge}", color=ft.colors.ORANGE_300))

#         # Stage log
#         results_col.controls.append(ft.Divider(height=16))
#         results_col.controls.append(ft.Text("Stage Log", weight="bold", size=15))
#         for log in result.get("logs", []):
#             results_col.controls.append(
#                 ft.Text(log, size=12, font_family="monospace", color=ft.colors.CYAN_200)
#             )

#         # Switch to results tab
#         tabs_ctrl.selected_index = 1
#         page.update()

#     # ── Side panel ───────────────────────────────────────────────────────────
#     side_panel_col = ft.Column(spacing=10, scroll=ft.ScrollMode.AUTO, expand=True)
#     side_container = ft.Container(
#         content=side_panel_col,
#         bgcolor="#161b22",
#         padding=16,
#         border_radius=10,
#         border=ft.border.all(1, "#30363d"),
#         visible=False,
#         width=340,
#         expand=False,
#     )

#     def show_side_panel(app: dict, is_retail: bool):
#         side_panel_col.controls.clear()

#         if is_retail:
#             title   = app.get("name", "N/A")
#             details = [
#                 ("City",       app.get("city", "N/A")),
#                 ("Gender",     app.get("gender", "N/A")),
#                 ("Age",        app.get("age", "N/A")),
#                 ("DOB",        app.get("date_of_birth", "N/A")),
#                 ("PAN",        app.get("pan", "N/A")),
#                 ("Mobile",     app.get("mobile", "N/A")),
#                 ("Email",      app.get("email", "N/A")),
#                 ("Employment", app.get("employment_type", "N/A")),
#                 ("Loan Type",  app.get("loan_type", app.get("type", "N/A"))),
#                 ("Purpose",    app.get("loan_purpose", "N/A")),
#                 ("CIBIL",      app.get("cibil", "N/A")),
#                 ("Income/mo",  fmt_inr(app.get("monthly_income", 0))),
#                 ("Loan Amt",   fmt_inr(app.get("loan_amt", 0))),
#                 ("Tenure",     f"{app.get('tenure_months', 'N/A')} months"),
#                 ("Existing EMI", fmt_inr(app.get("existing_emi", 0))),
#             ]
#         else:
#             title   = app.get("name", "N/A")
#             details = [
#                 ("City",      app.get("city", "N/A")),
#                 ("Industry",  app.get("industry", "N/A")),
#                 ("PAN",       app.get("pan", "N/A")),
#                 ("GSTIN",     app.get("gstin", "N/A")),
#                 ("Mobile",    app.get("mobile", "N/A")),
#                 ("Email",     app.get("email", "N/A")),
#                 ("Promoter",  app.get("promoter_name", "N/A")),
#                 ("CIBIL",     app.get("cibil", "N/A")),
#                 ("Loan Type", app.get("loan_type", app.get("type", "N/A"))),
#                 ("Purpose",   app.get("loan_purpose", "N/A")),
#                 ("Turnover",  fmt_inr(app.get("turnover", 0))),
#                 ("Loan Amt",  fmt_inr(app.get("loan_amt", 0))),
#                 ("Vintage",   f"{app.get('vintage', 'N/A')} years"),
#                 ("Collateral", fmt_inr(app.get("collateral", 0))),
#             ]

#         side_panel_col.controls.append(
#             ft.Text(title, size=16, weight="bold", color=ft.colors.CYAN_300)
#         )
#         side_panel_col.controls.append(ft.Divider(height=8))
#         for lbl, val in details:
#             side_panel_col.controls.append(kv_row(lbl, str(val)))
#         side_panel_col.controls.append(
#             ft.TextButton("✕  Close", on_click=lambda _: hide_side_panel())
#         )

#         side_container.visible = True
#         page.update()

#     def hide_side_panel():
#         side_container.visible = False
#         page.update()

#     # ── Retail section ───────────────────────────────────────────────────────
#     retail_dd_ref     = ft.Ref[ft.Dropdown]()
#     retail_search_ref = ft.Ref[ft.TextField]()
#     retail_progress   = ft.ProgressRing(visible=False, width=28, height=28)
#     retail_status     = ft.Text("Ready", size=13, color=ft.colors.GREEN_300)
#     selected_retail   = [None]

#     def build_retail_options(query: str = "") -> list:
#         q = query.lower()
#         filtered = (
#             [a for a in RETAIL_SAMPLES if
#              q in a.get("city", "").lower() or
#              q in a.get("name", "").lower() or
#              q in a.get("employment_type", "").lower() or
#              q in a.get("loan_type", a.get("type", "")).lower() or
#              q in a.get("loan_purpose", "").lower()]
#             if q else RETAIL_SAMPLES
#         )
#         return [
#             ft.dropdown.Option(
#                 key=a["id"],
#                 text=f"{a['name']}  |  {a['city']}  |  {a.get('loan_type', a.get('type',''))}  |  "
#                      f"{fmt_inr(a.get('loan_amt',0))}  |  CIBIL {a.get('cibil','')}"
#             )
#             for a in filtered[:500]
#         ]

#     def on_retail_search(e):
#         retail_dd_ref.current.options = build_retail_options(retail_search_ref.current.value or "")
#         page.update()

#     def on_retail_select(e):
#         if not retail_dd_ref.current.value:
#             hide_side_panel()
#             return
#         app = next((a for a in RETAIL_SAMPLES if a["id"] == retail_dd_ref.current.value), None)
#         if app:
#             selected_retail[0] = app
#             show_side_panel(app, is_retail=True)

#     def process_retail(_e):
#         app = selected_retail[0]
#         if not app:
#             page.show_snack_bar(ft.SnackBar(ft.Text("Please select a retail applicant first")))
#             return
#         active_mode[0] = "retail"
#         retail_progress.visible = True
#         retail_status.value     = "Processing…"
#         page.update()
#         try:
#             result = _retail_pipeline.run(app)
#             show_results(result, "retail")
#             retail_status.value = f"Done – {result.get('decision','N/A')}"
#         except Exception as ex:
#             retail_status.value = f"Error: {ex}"
#         finally:
#             retail_progress.visible = False
#             page.update()

#     # ── SME section ──────────────────────────────────────────────────────────
#     sme_dd_ref     = ft.Ref[ft.Dropdown]()
#     sme_search_ref = ft.Ref[ft.TextField]()
#     sme_progress   = ft.ProgressRing(visible=False, width=28, height=28)
#     sme_status     = ft.Text("Ready", size=13, color=ft.colors.GREEN_300)
#     selected_sme   = [None]

#     def build_sme_options(query: str = "") -> list:
#         q = query.lower()
#         filtered = (
#             [a for a in SME_SAMPLES if
#              q in a.get("city", "").lower() or
#              q in a.get("name", "").lower() or
#              q in a.get("industry", "").lower() or
#              q in a.get("loan_type", a.get("type", "")).lower() or
#              q in a.get("loan_purpose", "").lower()]
#             if q else SME_SAMPLES
#         )
#         return [
#             ft.dropdown.Option(
#                 key=a["id"],
#                 text=f"{a['name']}  |  {a['city']}  |  {a.get('industry','')}  |  "
#                      f"{a.get('loan_type', a.get('type',''))}  |  {fmt_inr(a.get('loan_amt',0))}"
#             )
#             for a in filtered[:500]
#         ]

#     def on_sme_search(e):
#         sme_dd_ref.current.options = build_sme_options(sme_search_ref.current.value or "")
#         page.update()

#     def on_sme_select(e):
#         if not sme_dd_ref.current.value:
#             hide_side_panel()
#             return
#         app = next((a for a in SME_SAMPLES if a["id"] == sme_dd_ref.current.value), None)
#         if app:
#             selected_sme[0] = app
#             show_side_panel(app, is_retail=False)

#     def process_sme(_e):
#         app = selected_sme[0]
#         if not app:
#             page.show_snack_bar(ft.SnackBar(ft.Text("Please select an SME applicant first")))
#             return
#         active_mode[0] = "sme"
#         sme_progress.visible = True
#         sme_status.value     = "Processing…"
#         page.update()
#         try:
#             result = _sme_pipeline.run(app)
#             show_results(result, "sme")
#             sme_status.value = f"Done – {result.get('decision','N/A')}"
#         except Exception as ex:
#             sme_status.value = f"Error: {ex}"
#         finally:
#             sme_progress.visible = False
#             page.update()

#     # ── STT / translate ──────────────────────────────────────────────────────
#     def translate_results(_e):
#         text = "\n".join([
#             c.controls[-1].value
#             for c in results_col.controls
#             if isinstance(c, ft.Row) and c.controls
#         ])
#         hindi = translate_to_hindi(text[:2000])
#         results_col.controls.append(ft.Divider())
#         results_col.controls.append(
#             ft.Container(
#                 ft.Column([
#                     ft.Text("हिंदी अनुवाद", weight="bold", color=ft.colors.YELLOW_200, size=16),
#                     ft.Text(hindi, size=13, selectable=True),
#                 ]),
#                 bgcolor="#161b22",
#                 padding=14,
#                 border_radius=8,
#             )
#         )
#         page.update()

#     # ── Layout helpers ───────────────────────────────────────────────────────
#     def section_title(text: str) -> ft.Text:
#         return ft.Text(text, size=18, weight="bold", color=ft.colors.CYAN_300)

#     def card(content: ft.Control) -> ft.Container:
#         return ft.Container(
#             content=content,
#             bgcolor="#161b22",
#             padding=20,
#             border_radius=12,
#             border=ft.border.all(1, "#30363d"),
#         )

#     # ── Applications tab ────────────────────────────────────────────────────
#     retail_section = card(ft.Column([
#         section_title("🏦  Retail Loan Applicants"),
#         ft.Text(f"{len(RETAIL_SAMPLES):,} applicants loaded", size=12, color=ft.colors.GREY_500),
#         ft.TextField(
#             ref=retail_search_ref,
#             label="🔍  Search by name / city / loan type / purpose",
#             on_change=on_retail_search,
#             border_color="#30363d",
#             focused_border_color=ft.colors.CYAN_400,
#         ),
#         ft.Dropdown(
#             ref=retail_dd_ref,
#             label="Select Retail Applicant",
#             options=build_retail_options(),
#             on_change=on_retail_select,
#             bgcolor="#0d1117",
#         ),
#         ft.Row([
#             ft.ElevatedButton(
#                 "▶  Process Retail",
#                 on_click=process_retail,
#                 icon=ft.icons.PLAY_CIRCLE_FILLED,
#                 bgcolor=ft.colors.CYAN_700,
#                 color=ft.colors.WHITE,
#                 height=46,
#             ),
#             retail_progress,
#             retail_status,
#         ], spacing=14),
#     ], spacing=14))

#     sme_section = card(ft.Column([
#         section_title("🏭  SME / Corporate Trade Finance Applicants"),
#         ft.Text(f"{len(SME_SAMPLES):,} applicants loaded", size=12, color=ft.colors.GREY_500),
#         ft.TextField(
#             ref=sme_search_ref,
#             label="🔍  Search by name / city / industry / loan type",
#             on_change=on_sme_search,
#             border_color="#30363d",
#             focused_border_color=ft.colors.AMBER_400,
#         ),
#         ft.Dropdown(
#             ref=sme_dd_ref,
#             label="Select SME Applicant",
#             options=build_sme_options(),
#             on_change=on_sme_select,
#             bgcolor="#0d1117",
#         ),
#         ft.Row([
#             ft.ElevatedButton(
#                 "▶  Process SME",
#                 on_click=process_sme,
#                 icon=ft.icons.PLAY_CIRCLE_FILLED,
#                 bgcolor=ft.colors.AMBER_700,
#                 color=ft.colors.WHITE,
#                 height=46,
#             ),
#             sme_progress,
#             sme_status,
#         ], spacing=14),
#     ], spacing=14))

#     left_col = ft.Column(
#         [retail_section, sme_section],
#         spacing=20,
#         expand=2,
#         scroll=ft.ScrollMode.AUTO,
#     )

#     applications_tab = ft.Row(
#         [left_col, side_container],
#         spacing=16,
#         expand=True,
#         vertical_alignment=ft.CrossAxisAlignment.START,
#     )

#     # ── Results tab ─────────────────────────────────────────────────────────
#     results_tab = ft.Column([
#         ft.Container(
#             content=results_col,
#             expand=True,
#             bgcolor="#161b22",
#             padding=20,
#             border_radius=12,
#             border=ft.border.all(1, "#30363d"),
#         ),
#         ft.Row([
#             ft.ElevatedButton(
#                 "🌐  Translate to हिंदी",
#                 on_click=translate_results,
#                 icon=ft.icons.TRANSLATE,
#                 bgcolor="#21262d",
#             ),
#             ft.ElevatedButton(
#                 "🗑  Clear",
#                 on_click=lambda _: [results_col.controls.clear(), page.update()],
#                 bgcolor="#21262d",
#             ),
#         ], spacing=12),
#     ], expand=True, spacing=12)

#     # ── Tabs ────────────────────────────────────────────────────────────────
#     tabs_ctrl = ft.Tabs(
#         selected_index=0,
#         animation_duration=200,
#         tabs=[
#             ft.Tab(text="  Applications  ", content=applications_tab),
#             ft.Tab(text="  Results  ",      content=results_tab),
#         ],
#         expand=True,
#     )

#     # ── Header ──────────────────────────────────────────────────────────────
#     header = ft.Container(
#         ft.Row([
#             ft.Text("  Loan Processing Demo", size=26, weight="bold", color=ft.colors.CYAN_300),
#             ft.Text("Retail + SME | AI-Powered Multi-Agent Pipeline", size=13, color=ft.colors.GREY_500),
#         ], alignment=ft.MainAxisAlignment.SPACE_BETWEEN),
#         bgcolor="#161b22",
#         padding=ft.padding.symmetric(horizontal=28, vertical=14),
#         border=ft.border.only(bottom=ft.border.BorderSide(1, "#30363d")),
#     )

#     page.add(
#         ft.Column([
#             header,
#             ft.Container(content=tabs_ctrl, expand=True, padding=20),
#         ], spacing=0, expand=True)
#     )
#     page.update()


# ft.app(target=main)

# =========================================================================================================================
# OR
#=========================================================================================================================
# main.py - FINAL COMPLETE VERSION with FULL FORMS
# Retail + SME pipelines + searchable dropdowns + side panel + full dashboard + visualizations

import flet as ft
import json
import time
import random
import base64
from io import BytesIO
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from retail_pipeline import RetailPipeline
from sme_pipeline import SMEPipeline
from sarvam_utils import stt_from_file, translate_to_hindi

# ───────────────────────────────────────────────
# Load synthetic applicants (run synthetic_data_generator.py first)
# ───────────────────────────────────────────────
try:
    with open("retail_applicants.json", "r", encoding="utf-8") as f:
        retail_samples = json.load(f)
    with open("sme_applicants.json", "r", encoding="utf-8") as f:
        sme_samples = json.load(f)
except FileNotFoundError:
    retail_samples = []
    sme_samples = []
    print("Warning: JSON files missing – run synthetic_data_generator.py")

# ───────────────────────────────────────────────
# Visualization Functions (all included)
# ───────────────────────────────────────────────

def sankey_pipeline_diagram(is_retail=True):
    if is_retail:
        stages = ["Intake", "KYC", "Income", "Bureau", "Property", "Decision", "Sanction", "Docs", "Disbursement"]
        counts = [1200, 1050, 920, 850, 720, 680, 620, 590, 550]
    else:
        stages = ["Intake", "KYC", "Financial", "Bureau", "Collateral", "Underwriting", "Sanction", "Docs", "Disbursement"]
        counts = [800, 720, 650, 590, 540, 500, 460, 430, 400]

    fig = go.Figure(data=[go.Sankey(
        node=dict(pad=15, thickness=20, line=dict(color="black", width=0.5), label=stages, color=["#636EFA"]*len(stages)),
        link=dict(source=list(range(len(stages)-1)), target=list(range(1, len(stages))), value=counts[1:],
                  color=[f"rgba(99,110,250,{v/max(counts[1:]):.2f})" for v in counts[1:]])
    )])

    fig.update_layout(title_text=f"{'Retail' if is_retail else 'SME'} Pipeline Flow", font_size=12, height=500, margin=dict(l=20,r=20,t=80,b=20))
    return ft.PlotlyChart(fig, expand=True)

def foir_dscr_gauge(value: float, title: str = "FOIR", max_value: float = 60):
    fig = go.Figure(go.Indicator(mode="gauge+number", value=value, domain={'x': [0, 1], 'y': [0, 1]}, title={'text': title},
                                 gauge={'axis': {'range': [0, max_value * 1.2]}, 'bar': {'color': "darkblue"},
                                        'steps': [{'range': [0, max_value * 0.7], 'color': "lightgreen"},
                                                  {'range': [max_value * 0.7, max_value], 'color': "orange"},
                                                  {'range': [max_value, max_value * 1.2], 'color': "red"}],
                                        'threshold': {'line': {'color': "red", 'width': 4}, 'thickness': 0.75, 'value': max_value}}))
    fig.update_layout(height=300, margin=dict(l=20,r=20,t=50,b=20))
    return ft.PlotlyChart(fig, expand=True)

def radar_scorecard(result, is_retail=True):
    if is_retail:
        metrics = ["CIBIL", "FOIR", "Lead", "Income"]
        values = [result.get("cibil_score",700)/9, 100-result.get("foir_post_loan",40), result.get("lead_score",70), random.uniform(60,90)]
    else:
        metrics = ["CIBIL", "DSCR", "Vintage", "Health"]
        values = [result.get("promoter_cibil_score",700)/9, result.get("dscr",1.4)*30, result.get("vintage",7)*5, result.get("financial_health_score",70)]
    fig = go.Figure(go.Scatterpolar(r=values, theta=metrics, fill='toself'))
    fig.update_layout(polar=dict(radialaxis=dict(range=[0,100])), showlegend=False, height=350)
    return ft.PlotlyChart(fig, expand=True)

def rejection_reasons_chart():
    df = pd.DataFrame({"Reason": ["Low CIBIL","High FOIR","LTV","Vintage","Fraud","Other"], "Count": [320,180,140,90,60,45]})
    pie = px.pie(df, values="Count", names="Reason", title="Rejection Reasons", hole=0.4)
    treemap = px.treemap(df, path=["Reason"], values="Count", title="Rejection Treemap")
    pie.update_layout(height=350); treemap.update_layout(height=350)
    return ft.Column([ft.PlotlyChart(pie), ft.PlotlyChart(treemap)], spacing=10)

def portfolio_treemap(by="city"):
    if by == "city":
        df = pd.DataFrame({"City": ["Bengaluru","Mumbai","Delhi","Hyderabad","Others"], "Amount": [145,92,78,65,220]})
        fig = px.treemap(df, path=["City"], values="Amount", title="Portfolio by City")
    else:
        df = pd.DataFrame({"Industry": ["IT","Manufacturing","Retail","Others"], "Amount": [180,135,98,187]})
        fig = px.treemap(df, path=["Industry"], values="Amount", title="Portfolio by Industry")
    fig.update_layout(height=400)
    return ft.PlotlyChart(fig, expand=True)

def dpd_trend_chart():
    df = pd.DataFrame({
        "Month": ["Jan","Feb","Mar","Apr","May","Jun"],
        "0-30": [620,580,550,520,490,460],
        "31-60": [140,130,120,110,100,90],
        "61-90": [60,55,50,45,40,35],
        "90+": [30,28,25,22,20,18]
    })
    df_melt = df.melt(id_vars="Month", var_name="Bucket", value_name="Count")
    fig = px.area(df_melt, x="Month", y="Count", color="Bucket", title="DPD Trend")
    fig.update_layout(height=400)
    return ft.PlotlyChart(fig, expand=True)

# ───────────────────────────────────────────────
# Main App
# ───────────────────────────────────────────────

def main(page: ft.Page):
    page.title = "Loan Processing Dashboard – Retail & SME"
    page.theme_mode = ft.ThemeMode.DARK
    page.padding = 20
    page.bgcolor = ft.colors.with_opacity(0.96, ft.colors.BLUE_GREY_900)

    picked_file = [None]
    current_result = [None, None]  # [result, is_retail]

    file_picker = ft.FilePicker(on_result=lambda e: setattr(picked_file, 0, e.files[0].path) if e.files else None)
    page.overlay.append(file_picker)

    def pick_wav(_): file_picker.pick_files(allowed_extensions=["wav"])

    def start_recording(_):
        page.run_js("""
            let chunks = [];
            navigator.mediaDevices.getUserMedia({audio:true}).then(stream => {
                let recorder = new MediaRecorder(stream);
                recorder.ondataavailable = e => chunks.push(e.data);
                recorder.onstop = () => {
                    let blob = new Blob(chunks, {type:'audio/wav'});
                    let url = URL.createObjectURL(blob);
                    let a = document.createElement('a');
                    a.href = url; a.download = 'recorded_input.wav'; a.click();
                    window.dispatchEvent(new CustomEvent('recordDone', {detail: 'recorded_input.wav'}));
                };
                recorder.start();
                setTimeout(() => recorder.stop(), 8000);
            }).catch(err => alert('Mic error'));
        """)

    def on_record_done(e):
        picked_file[0] = "recorded_input.wav"
        page.show_snack_bar(ft.SnackBar(ft.Text("Recording saved")))

    page.on_event("recordDone", on_record_done)

    def run_stt(target):
        if picked_file[0]:
            text = stt_from_file(picked_file[0])
            target.current.value = text
            page.update()

    def translate_dashboard(_):
        text = "\n".join([str(c.value or "") for c in results_content.controls if hasattr(c, "value")])
        hindi = translate_to_hindi(text)
        results_content.controls.append(ft.Text(f"हिंदी:\n{hindi}", color=ft.colors.YELLOW_300))
        page.update()

    def export_all_charts(_):
        page.show_snack_bar(ft.SnackBar(ft.Text("Exporting charts as PNG/PDF... (mock - add real logic)")))

    # Side panel
    side_panel = ft.Container(visible=False, width=380, bgcolor=ft.colors.with_opacity(0.92, ft.colors.BLUE_GREY_800), padding=16, border_radius=12)

    def show_side_panel(applicant, is_retail=True):
        side_panel.content.controls.clear()
        title = f"{'Retail' if is_retail else 'SME'} Applicant Details"
        details = []
        for k, v in applicant.items():
            if k not in ["id", "created"]:
                details.append(f"{k.replace('_',' ').title()}: {v}")
        side_panel.content.controls.extend([
            ft.Text(title, size=18, weight="bold"),
            ft.Divider(),
            *[ft.Text(d, size=13) for d in details],
            ft.ElevatedButton("Close", on_click=lambda _: setattr(side_panel, "visible", False))
        ])
        side_panel.visible = True
        page.update()

    # ── Retail Form ──────────────────────────────────────────────────
    retail_search = ft.Ref[ft.TextField]()
    retail_dd = ft.Ref[ft.Dropdown]()
    retail_name = ft.Ref[ft.TextField]()

    def update_retail_dropdown(e):
        query = retail_search.current.value.lower() if retail_search.current.value else ""
        filtered = [
            app for app in retail_samples
            if query in app.get("city", "").lower()
            or query in app.get("employment_type", "").lower()
            or query in app.get("name", "").lower()
            or query in app.get("type", "").lower()
            or query in app.get("loan_purpose", "").lower()
        ]
        retail_dd.current.options = [
            ft.dropdown.Option(
                key=app["id"],
                text=f"{app['name']} | {app['city']} | {app['type']} | ₹{app['loan_amt']:,} | {app.get('employment_type','Salaried')} | {app.get('loan_purpose','Personal')}"
            ) for app in filtered[:300]
        ]
        page.update()

    def on_retail_select(e):
        if not retail_dd.current.value:
            side_panel.visible = False
            page.update()
            return
        app = next(a for a in retail_samples if a["id"] == retail_dd.current.value)
        show_side_panel(app, is_retail=True)

    def process_retail(e):
        if not retail_dd.current.value:
            status_text.value = "Select applicant"
            status_text.color = ft.colors.RED_400
            page.update()
            return

        app = next(a for a in retail_samples if a["id"] == retail_dd.current.value)
        app = app.copy()
        app["full_name"] = retail_name.current.value or app["name"]

        progress.visible = True
        status_text.value = "Processing Retail..."
        status_text.color = ft.colors.AMBER_300
        results_content.controls.clear()
        page.update()

        result = RetailPipeline().run(app)
        current_result[0] = result
        current_result[1] = True
        create_dashboard(result, is_retail=True)

        progress.visible = False
        status_text.value = "Retail complete"
        status_text.color = ft.colors.GREEN_300
        page.update()

    retail_form = ft.Column(spacing=14, controls=[
        ft.TextField(ref=retail_search, label="Search by city / employment / name / purpose", on_change=update_retail_dropdown, width=520),
        ft.Dropdown(ref=retail_dd, label="Select Retail Applicant", options=[], width=520, on_change=on_retail_select),
        ft.TextField(ref=retail_name, label="Override Name (optional)"),
        ft.Row([ft.ElevatedButton("Process Retail", on_click=process_retail, icon=ft.icons.PLAY_ARROW_ROUNDED, width=300, height=48),
                progress, status_text], alignment="center")
    ])

    # ── SME Form ─────────────────────────────────────────────────────
    sme_search = ft.Ref[ft.TextField]()
    sme_dd = ft.Ref[ft.Dropdown]()
    sme_name = ft.Ref[ft.TextField]()

    def update_sme_dropdown(e):
        query = sme_search.current.value.lower() if sme_search.current.value else ""
        filtered = [
            app for app in sme_samples
            if query in app.get("city", "").lower()
            or query in app.get("industry", "").lower()
            or query in app.get("name", "").lower()
            or query in app.get("type", "").lower()
            or query in app.get("loan_purpose", "").lower()
        ]
        sme_dd.current.options = [
            ft.dropdown.Option(
                key=app["id"],
                text=f"{app['name']} | {app['city']} | {app['industry']} | {app['type']} | ₹{app['loan_amt']:,}"
            ) for app in filtered[:300]
        ]
        page.update()

    def on_sme_select(e):
        if not sme_dd.current.value:
            side_panel.visible = False
            page.update()
            return
        app = next(a for a in sme_samples if a["id"] == sme_dd.current.value)
        show_side_panel(app, is_retail=False)

    def process_sme(e):
        if not sme_dd.current.value:
            status_text.value = "Select applicant"
            status_text.color = ft.colors.RED_400
            page.update()
            return

        app = next(a for a in sme_samples if a["id"] == sme_dd.current.value)
        app = app.copy()
        app["business_name"] = sme_name.current.value or app["name"]

        progress.visible = True
        status_text.value = "Processing SME..."
        status_text.color = ft.colors.AMBER_300
        results_content.controls.clear()
        page.update()

        result = SMEPipeline().run(app)
        current_result[0] = result
        current_result[1] = False
        create_dashboard(result, is_retail=False)

        progress.visible = False
        status_text.value = "SME complete"
        status_text.color = ft.colors.GREEN_300
        page.update()

    sme_form = ft.Column(spacing=14, controls=[
        ft.TextField(ref=sme_search, label="Search by city / industry / name / purpose", on_change=update_sme_dropdown, width=520),
        ft.Dropdown(ref=sme_dd, label="Select SME Applicant", options=[], width=520, on_change=on_sme_select),
        ft.TextField(ref=sme_name, label="Override Business Name (optional)"),
        ft.Row([ft.ElevatedButton("Process SME", on_click=process_sme, icon=ft.icons.PLAY_ARROW_ROUNDED, width=300, height=48),
                progress, status_text], alignment="center")
    ])

    # Dashboard content
    results_content = ft.Column(scroll=ft.ScrollMode.AUTO, spacing=20, expand=True)

    def create_dashboard(result=None, is_retail=True):
        results_content.controls.clear()
        if not result:
            results_content.controls.append(ft.Text("Run a pipeline to see dashboard", size=18))
            page.update()
            return

        def animated_card(content):
            return ft.Card(
                content=ft.Container(content=content, padding=12, animate_opacity=True, opacity=0),
                elevation=2
            )

        sankey = animated_card(sankey_pipeline_diagram(is_retail))
        gauge1 = animated_card(foir_dscr_gauge(result.get("foir_post_loan", 38.2) if is_retail else result.get("dscr", 1.45)))
        gauge2 = animated_card(ltv_gauge(result.get("ltv_ratio", 68)))
        radar = animated_card(radar_scorecard(result, is_retail))
        rejection = animated_card(rejection_reasons_chart())
        treemap_city = animated_card(portfolio_treemap("city"))
        treemap_ind = animated_card(portfolio_treemap("industry"))
        dpd = animated_card(dpd_trend_chart())

        results_content.controls.extend([
            ft.Text("Loan Processing Dashboard", size=24, weight="bold"),
            ft.Row([sankey], alignment="center"),
            ft.Row([gauge1, gauge2], spacing=15, wrap=True),
            ft.Row([radar, treemap_city], spacing=15, wrap=True),
            ft.Row([treemap_ind, dpd], spacing=15, wrap=True),
            ft.ElevatedButton("Export Dashboard (PNG + PDF)", on_click=export_all_charts, icon=ft.icons.DOWNLOAD)
        ])

        page.update()

    # Tabs layout
    tabs = ft.Tabs(
        selected_index=0,
        tabs=[
            ft.Tab(text="Retail Loans", content=retail_form),
            ft.Tab(text="SME Loans", content=sme_form),
            ft.Tab(text="Dashboard", content=results_content),
        ],
        expand=True
    )

    page.add(
        ft.Container(
            content=ft.Column([
                ft.Text("Loan Processing Dashboard", size=28, weight="bold"),
                tabs
            ], spacing=20),
            padding=24,
            expand=True
        )
    )

    page.update()

ft.app(target=main)













